// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0RJftmCJ330UlcO2fIz1Tl2uMgzR2QhA',
    appId: '1:437077868565:web:d29f385b55c27cb5420e1c',
    messagingSenderId: '437077868565',
    projectId: 'smarttask-4136d',
    authDomain: 'smarttask-4136d.firebaseapp.com',
    storageBucket: 'smarttask-4136d.firebasestorage.app',
    measurementId: 'G-5KXGC312LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtC98bLYQ-oJpDecZrGExqD77uUCnNauo',
    appId: '1:437077868565:android:933711345be08e58420e1c',
    messagingSenderId: '437077868565',
    projectId: 'smarttask-4136d',
    storageBucket: 'smarttask-4136d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuigsmjBqh2NKNfddcE22oHAdxqaXFzAM',
    appId: '1:437077868565:ios:0c18b298bd517b2c420e1c',
    messagingSenderId: '437077868565',
    projectId: 'smarttask-4136d',
    storageBucket: 'smarttask-4136d.firebasestorage.app',
    iosBundleId: 'com.example.t4Baitap2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0RJftmCJ330UlcO2fIz1Tl2uMgzR2QhA',
    appId: '1:437077868565:web:f7a44f80dfecabf5420e1c',
    messagingSenderId: '437077868565',
    projectId: 'smarttask-4136d',
    authDomain: 'smarttask-4136d.firebaseapp.com',
    storageBucket: 'smarttask-4136d.firebasestorage.app',
    measurementId: 'G-TGPGJELY51',
  );
}
